# Generated by Django 5.1.4 on 2025-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("plant_type", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="plant_image/"),
                ),
                (
                    "sunlight",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Light"),
                            ("MEDIUM", "Medium Light"),
                            ("HIGH", "Bright Light"),
                        ],
                        max_length=50,
                    ),
                ),
                ("soil", models.CharField(max_length=500)),
                (
                    "water_frequency",
                    models.IntegerField(help_text="Number of days between watering"),
                ),
                ("fertilizer_instructions", models.TextField()),
                ("pruning_instructions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
