# Generated by Django 5.1.4 on 2025-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="water_frequency",
            field=models.IntegerField(help_text="Number of days per week"),
        ),
    ]
