# Generated by Django 5.1.4 on 2025-01-15 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0006_remove_gardenplant_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WateringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_watering_date", models.DateField()),
                ("frequency_in_days", models.IntegerField(default=7)),
                ("last_watered_date", models.DateField(blank=True, null=True)),
                (
                    "garden_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watering_schedules",
                        to="garden.gardenplant",
                    ),
                ),
            ],
        ),
    ]
