# Generated by Django 5.1.4 on 2025-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0008_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="plant",
            name="harvest_date",
            field=models.DateField(
                blank=True, help_text="Expected harvest date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="maintenance_task",
            field=models.TextField(
                blank=True,
                help_text="Maintenance tasks for the plant (e.g., pruning, fertilizing).",
            ),
        ),
    ]
