# Generated by Django 5.1.4 on 2025-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0009_remove_plant_created_at_remove_plant_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="harvest_date",
        ),
        migrations.AddField(
            model_name="plant",
            name="number_of_days_to_Harvest",
            field=models.IntegerField(
                blank=True, help_text="Expected days harvest", null=True
            ),
        ),
    ]
