# Generated by Django 5.1.4 on 2025-01-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0013_gardenplant_growth_stage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gardenplant",
            name="maintenance_completed",
        ),
    ]
