# Generated by Django 5.1.4 on 2025-01-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0016_delete_taskcompletion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="task_type",
        ),
    ]
