# Generated by Django 5.1.4 on 2025-01-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0017_remove_notification_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="image",
        ),
    ]
