# Generated by Django 5.1.4 on 2025-01-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0018_remove_plant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plant_image/"),
        ),
    ]
