# Generated by Django 5.1.4 on 2025-02-04 18:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0020_alter_plant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="images/"
            ),
        ),
    ]
